### ISSUE TITLE
HTTPS Cert Issue

### ISSUE THREAD

**Issue by rahulsahay19** [robrich/https-aspnet-core-docker-deep-dive#1]
Hi Sir,

I have been trying your couple of examples but couldn't get success. I am bit new to this setup. I am trying below use case, which is almost same how you have explained in your examples. 

Dockerfile

```.dockerfile
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src

COPY ["Poseidon.Api/NuGet.config", "Poseidon.Api/"]
COPY ["kognifai.Authentication/kognifai.Authentication.csproj", "kognifai.Authentication/"]
COPY ["kognifai.ClientCredentials/kognifai.ClientCredentials.csproj", "kognifai.ClientCredentials/"]
COPY ["Poseidon.Api.Storage.Definitions/Poseidon.Api.Storage.Definitions.csproj", "Poseidon.Api.Storage.Definitions/"]
COPY ["Poseidon.Api.Storage.LiteDb/Poseidon.Api.Storage.LiteDb.csproj", "Poseidon.Api.Storage.LiteDb/"]
COPY ["Poseidon.Api.Storage.CosmosDb/Poseidon.Api.Storage.CosmosDb.csproj", "Poseidon.Api.Storage.CosmosDb/"]

COPY ["Poseidon.Api/Poseidon.Api.csproj", "Poseidon.Api/"]

RUN dotnet restore "Poseidon.Api/Poseidon.Api.csproj"
COPY . .
WORKDIR "/src/Poseidon.Api"
RUN dotnet build "Poseidon.Api.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Poseidon.Api.csproj" -c Release -o /app

FROM base AS final

# untrusted dev cert
COPY --from=build /root/.dotnet/corefx/cryptography /root/.dotnet/corefx/cryptography

WORKDIR /app

COPY --from=publish /app .

ENTRYPOINT ["dotnet", "Poseidon.Api.dll"]
```
Docker Override

```
version: '3.4'

services:
  poseidonapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=9443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=poseidon
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/docker-devcert.pfx
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
```
and

Docker-Compose 

```
version: '3.4'

services:
  poseidonapi:
    image: ${DOCKER_REGISTRY}pnext-test:dev
    build:
      context: .
      dockerfile: Poseidon.Api/Dockerfile    
```

I also have deploy.cmd for composing this up.

```
dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\docker-devcert.pfx -p poseidon
dotnet dev-certs https --trust
dotnet user-secrets -p poseidon.api\poseidon.api.csproj set "Kestrel:Certificates:Development:Password" "poseidon"
SETX APPDATA %AppData%
docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build --force-recreate
```
So, when I run the same, it prints output correctly like shown below.

![image](https://user-images.githubusercontent.com/3886381/69218673-3bd4f200-0b97-11ea-9ea8-d7efdbb175c6.png)

And, comes like 

![image](https://user-images.githubusercontent.com/3886381/69218861-98d0a800-0b97-11ea-8dd8-1176fe89ec0b.png)

Also, clicking on certificate gives 

![image](https://user-images.githubusercontent.com/3886381/69218909-bbfb5780-0b97-11ea-856c-779266d3e2e1.png)

Is there any thing I am missing with this setup. Kindly let me know your thoughts to it.

Thanks,
Rahul
