### ISSUE TITLE
Need suggestion with litedb inside dockerfile

### ISSUE THREAD

**Issue by rahulsahay19** [robrich/https-aspnet-core-docker-deep-dive#2]
Hi,

I have one question not an issue. Actually, I am writing different docker files for different environment and in case of development, I use **LiteDb**. Hence, wanted to check whether you have tried dockerizing litedb as well. Because I didn't find any proper documentation around it. Thanks in advance.

Thanks,
Rahul

**Comment by robrich** [comment]
I haven't dockerized Litedb, but I have dockerized databases. The magic
sauce is using volumes and ensuring only one container runs at a time.
What's your Dockerfile look like so far? How can I help?

**Comment by rahulsahay19** [comment]
Hi Rob. Thanks for responding. My dockerfile file looks like 

```
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src

COPY ["kognifai.IdentityProvider/kognifai.IdentityProvider.csproj", "kognifai.IdentityProvider/"]
COPY ["kognifai.IdentityProvider/NuGet.config", "kognifai.IdentityProvider/"]
COPY ["kognifai.IdentityProvider/local.litedb", "kognifai.IdentityProvider/"]
COPY ["kognifai.Entitlements.API.Client/kognifai.Entitlements.API.Client.csproj", "kognifai.Entitlements.API.Client/"]
RUN dotnet restore "kognifai.IdentityProvider/kognifai.IdentityProvider.csproj"
COPY . .
WORKDIR "/src/kognifai.IdentityProvider"
RUN dotnet build "kognifai.IdentityProvider.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "kognifai.IdentityProvider.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "kognifai.IdentityProvider.dll"]
```
Here, I am exclusively copying lite db in image. And, when I inspect container that file is there. Strange thing is, when I run the same docker file from visual studio even without copying litedb. It works fine. Not sure, if its related with volume because for litedb, I don't have any volume configuration, basically I don't know, what will go inside.

```
version: '3.4'

services:
  kognifai.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTPS_PORT=9443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
    ports:
      - "9002:80"
      - "9445:443"
    volumes:
      - ${CERTIFICATE_PATH}:/root/.aspnet/https:ro
```
and Docker-compose

```
version: '3.4'

services:
  kognifai.identityprovider:
    image: ${DOCKER_REGISTRY}pnext-idp:dev
    build:
      context: .
      dockerfile: kognifai.IdentityProvider/Dockerfile
```
This is the current configuration. Thanks.
