### ISSUE TITLE
Facing issue while building the trust chain

### ISSUE THREAD

**Issue by rahulsahay19** [robrich/https-aspnet-core-docker-deep-dive#3]
Hi rob,

I was referring your video https://www.youtube.com/watch?v=oAf3_8k17E8&t=3138s and using the mkcert example for building the trust chain. I did the following things

1) Install mkcert
2) mkcert -install gave me rootCA.pem and rootCA.pem files.
3) I copied these in my root directory
4) Then, referred the same way in my docker file like this

```
FROM golang:alpine as cert

RUN apk update \
    && apk add git openssl nss-tools \
    && rm -rf /var/cache/apk/*

RUN cd /go && \
    go get -u github.com/FiloSottile/mkcert && \
    cd src/github.com/FiloSottile/mkcert && \
    go build -o /bin/mkcert

WORKDIR /root/.local/share/mkcert
# copied from %localappdata%\mkcert

COPY ./kognifai.IdentityProvider/rootCA*.pem /root/.local/share/mkcert/


# make a pfx with known password by making a pem/key then converting it
# includes minikube and docker ips
RUN mkcert -install \
    && mkcert -key-file docker-dev.key -cert-file docker-dev.pem minikube 192.168.184.148 localhost 127.0.0.1 idp \
    && openssl pkcs12 -export -out docker-dev.pfx -inkey docker-dev.key -in docker-dev.pem -certfile rootCA.pem -passout pass:poseidon


FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine as base

WORKDIR /src

COPY ["kognifai.IdentityProvider/kognifai.IdentityProvider.csproj", "kognifai.IdentityProvider/"]
COPY ["kognifai.IdentityProvider/NuGet.config", "kognifai.IdentityProvider/"]
COPY ["kognifai.Entitlements.API.Client/kognifai.Entitlements.API.Client.csproj", "kognifai.Entitlements.API.Client/"]
RUN dotnet restore "kognifai.IdentityProvider/kognifai.IdentityProvider.csproj"
COPY . ./
WORKDIR "/src/kognifai.IdentityProvider"
RUN dotnet build "kognifai.IdentityProvider.csproj" -c Debug -o /app

FROM base AS publish
RUN dotnet publish "kognifai.IdentityProvider.csproj" -c Debug -o /dist

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine

COPY --from=cert /bin/mkcert /bin/mkcert
# root cert but not root private key:
COPY --from=cert /root/.local/share/mkcert/rootCA.pem /root/.local/share/mkcert/rootCA.pem
COPY --from=cert /root/.local/share/mkcert/docker-dev.pfx /app/
# TODO: consider `chmod 600 *.pem and *.pfx`

# tell ASP.NET Core to use the cert
ENV Kestrel__Certificates__Default__Path=/app/docker-dev.pfx
ENV Kestrel__Certificates__Default__Password=poseidon

# trust root cert
RUN apk update \
    && apk add nss-tools \
    && rm -rf /var/cache/apk/* \
    && mkcert -install \
    && apk del nss-tools \
    && rm -rf /bin/mkcert


FROM base AS final

WORKDIR /app
VOLUME /app/kognifai.IdentityProvider/db
COPY --from=publish /dist /app

ENV ASPNETCORE_ENVIRONMENT Development
ENV ASPNETCORE_URLS https://+:9445;http://+:9002
EXPOSE 9002 9445

ENTRYPOINT ["dotnet", "kognifai.IdentityProvider.dll"]
```
with few docker override like

```
version: '3.4'

services:
  kognifai.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTPS_PORT=9445
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
           
    ports:
      - "9002:9002"
      - "9445:9445"      
    volumes:
      # - ${CERTIFICATE_PATH}:/root/.aspnet/https:ro
      - "./db:/app/kognifai.IdentityProvider/db"
```
When app starts it remain un-trusted on local machine like shown below

![image](https://user-images.githubusercontent.com/3886381/69906106-420f6d80-13e4-11ea-8a3c-8ae58c1a74ef.png)

Then, I thought to install pfx file locally with mkcert utility and import in local.
mkcert -pkcs12 localhost 
Then, imported the pfx in root folder with "changeit" password. And it looks perfect in certs

![image](https://user-images.githubusercontent.com/3886381/69906131-96b2e880-13e4-11ea-8778-ed017d0347e2.png)

But, the point is neither way its setting the build chain from the container to the host machine. Just wanted to check did you run anything extra on the host machine to trust the mkcert certificate locally.

Thanks,
Rahul

**Comment by rahulsahay19** [comment]
Fixed this. By mistake copied release build rather than debug build. Also, I have noticed one thing, out of two swagger endpoints authorized by mkcert and other one different project is via localhost. Principally, it should have been also by mkcert only. However, not sure why volume mapping for lite.db isn't working after this cert fix. Will see, if in debug mode volume mapping is required or something else is missing.

**Comment by robrich** [comment]
I suspect the line `FROM base as final` is not doing what you want as the
container right before it sets up the trust chain for the certs and this
new one includes your source code. If you remove this line then they become
one container with the trust chain and no source code in it making it much
lighter.

**Comment by rahulsahay19** [comment]
Yeah. That one I already removed, when I was comparing step by step with your example. that's why cert got trusted. But, my problem is its unable to detect local.litedb the volume, which I mapped. This is what I was thinking, whether i did any thing wrong here.

```FROM golang:alpine as cert

RUN apk update \
    && apk add git openssl nss-tools \
    && rm -rf /var/cache/apk/*

RUN cd /go && \
    go get -u github.com/FiloSottile/mkcert && \
    cd src/github.com/FiloSottile/mkcert && \
    go build -o /bin/mkcert

WORKDIR /root/.local/share/mkcert
# copied from %localappdata%\mkcert

COPY ./kognifai.IdentityProvider/rootCA*.pem /root/.local/share/mkcert/


# make a pfx with known password by making a pem/key then converting it
# includes minikube and docker ips
RUN mkcert -install \
    && mkcert -key-file docker-dev.key -cert-file docker-dev.pem dockernat 10.0.75.1 localhost 127.0.0.1 web \
    && openssl pkcs12 -export -out docker-dev.pfx -inkey docker-dev.key -in docker-dev.pem -certfile rootCA.pem -passout pass:poseidon


FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine as base

WORKDIR /src

COPY ["kognifai.IdentityProvider/kognifai.IdentityProvider.csproj", "kognifai.IdentityProvider/"]
COPY ["kognifai.IdentityProvider/NuGet.config", "kognifai.IdentityProvider/"]
COPY ["kognifai.Entitlements.API.Client/kognifai.Entitlements.API.Client.csproj", "kognifai.Entitlements.API.Client/"]
RUN dotnet restore "kognifai.IdentityProvider/kognifai.IdentityProvider.csproj"
COPY . ./
WORKDIR /src/kognifai.IdentityProvider
#RUN dotnet build "kognifai.IdentityProvider.csproj" -c Debug -o /app

#FROM base AS publish
RUN dotnet publish "kognifai.IdentityProvider.csproj" -c Debug -o /dist

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine

COPY --from=cert /bin/mkcert /bin/mkcert
# root cert but not root private key:
COPY --from=cert /root/.local/share/mkcert/rootCA.pem /root/.local/share/mkcert/rootCA.pem
COPY --from=cert /root/.local/share/mkcert/docker-dev.pfx /app/
# TODO: consider `chmod 600 *.pem and *.pfx`

# tell ASP.NET Core to use the cert
ENV Kestrel__Certificates__Default__Path=/app/docker-dev.pfx
ENV Kestrel__Certificates__Default__Password=poseidon

# trust root cert
RUN apk update \
    && apk add nss-tools \
    && rm -rf /var/cache/apk/* \
    && mkcert -install \
    && apk del nss-tools \
    && rm -rf /bin/mkcert


#FROM base AS final

WORKDIR /app
VOLUME /app/kognifai.IdentityProvider/db
COPY --from=base /dist /app

ENV ASPNETCORE_ENVIRONMENT Development
ENV ASPNETCORE_URLS https://+:9445;http://+:9002
EXPOSE 9002 9445

CMD ["dotnet", "kognifai.IdentityProvider.dll"]
```
and override looks like 

```
version: '3.4'

services:
  kognifai.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTPS_PORT=9445
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
           
    ports:
      - "9002:9002"
      - "9445:9445"      
    volumes:
      # - ${CERTIFICATE_PATH}:/root/.aspnet/https:ro
      - "./db:/app/kognifai.IdentityProvider/db"
      # - ".:/app/kognifai.IdentityProvider"
```
And, this is how I kept my project structured.

![image](https://user-images.githubusercontent.com/3886381/69916314-a3d0e580-147f-11ea-99af-53e5deab7816.png)
Hence issue seems to be with volume mapping. Tried with copy as well. But same result. Earlier when I was using copying the cert from local machine and then converting the same into crt like your example in the video. That time volume works. But, offcourse it fails when I make another call to different API because of trust chain issue. Hence, trying this mkcert example. I guess, something small am missing with volume configuration.

Thanks,
Rahul

**Comment by robrich** [comment]
In docker compose file try changing this line:

 - "./db:/app/kognifai.IdentityProvider/db"

to this:

 - "./db:/app/db"

**Comment by rahulsahay19** [comment]
not picking unfortunately. Also, when I do RUN ls after WORKDIR /app. It prints kognifai.IdentityProvider. But didn't pick up the file. I am basically running with this docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build --force-recreate.

**Comment by robrich** [comment]
What does the docker-compose.override.yml file look like?

**Comment by rahulsahay19** [comment]
Like this
```
version: '3.4'

services:
  kognifai.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTPS_PORT=9445
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
           
    ports:
      - "9002:9002"
      - "9445:9445"      
    volumes:
      # - ${CERTIFICATE_PATH}:/root/.aspnet/https:ro
      - "./db:/app/db"
      # - ".:/app/kognifai.IdentityProvider"
```

**Comment by rahulsahay19** [comment]
Like with your previous example volume works. It picks up the file
```FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine as base

WORKDIR /app
EXPOSE 9002
EXPOSE 9445

WORKDIR /ssl
COPY ./kognifai.IdentityProvider/docker-dev.pfx .

RUN apk update \
    && apk add ca-certificates openssl \
    && rm -rf /var/cache/apk/* \
    && openssl pkcs12 -in docker-dev.pfx -out docker-dev.pem -nokeys -nodes -passin pass:poseidon \
    && openssl pkcs12 -in docker-dev.pfx -out docker-dev.key -nocerts -nodes -passin pass:poseidon \
    && openssl pkcs12 -export -out docker-dev-nopass.pfx -inkey docker-dev.key -in docker-dev.pem -passout pass: \
    && chmod 644 * \
    && chmod 600 *.pfx

WORKDIR /src

COPY ["kognifai.IdentityProvider/kognifai.IdentityProvider.csproj", "kognifai.IdentityProvider/"]
COPY ["kognifai.IdentityProvider/NuGet.config", "kognifai.IdentityProvider/"]
COPY ["kognifai.Entitlements.API.Client/kognifai.Entitlements.API.Client.csproj", "kognifai.Entitlements.API.Client/"]
RUN dotnet restore "kognifai.IdentityProvider/kognifai.IdentityProvider.csproj"
COPY . ./
WORKDIR "/src/kognifai.IdentityProvider"
RUN dotnet build "kognifai.IdentityProvider.csproj" -c Release -o /app

FROM base AS publish
RUN dotnet publish "kognifai.IdentityProvider.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-alpine

COPY --from=base /ssl/docker-dev.pem /usr/local/share/ca-certificates/docker-dev.crt
COPY --from=base /ssl/docker-dev-nopass.pfx /root/.dotnet/corefx/cryptography/x509stores/my/
# DON'T COPY *.key !!!

# trust cert:
RUN apk update \
    && apk add ca-certificates \
    && rm -rf /var/cache/apk/* \
    && update-ca-certificates 2>/dev/null \
    && ls /etc/ssl/certs/*docker-dev* \
    && echo 'cert imported correctly if listed above'



FROM base AS final
WORKDIR /app
VOLUME /app/kognifai.IdentityProvider/db
COPY --from=publish /app .

ENTRYPOINT ["dotnet", "kognifai.IdentityProvider.dll"]
```
docker Override
```
version: '3.4'

services:
  kognifai.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTPS_PORT=9445
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
           
    ports:
      - "9002:9002"
      - "9445:9445"      
    volumes:
      # - ${CERTIFICATE_PATH}:/root/.aspnet/https:ro
      # - "./db:/app/db"
        - ".:/app/kognifai.IdentityProvider/db"
```
However, when I convert the same with mkcert this starts failing 
```
FROM golang:alpine as cert

RUN apk update \
    && apk add git openssl nss-tools \
    && rm -rf /var/cache/apk/*

RUN cd /go && \
    go get -u github.com/FiloSottile/mkcert && \
    cd src/github.com/FiloSottile/mkcert && \
    go build -o /bin/mkcert

WORKDIR /root/.local/share/mkcert
# copied from %localappdata%\mkcert

COPY ./kognifai.IdentityProvider/rootCA*.pem /root/.local/share/mkcert/


# make a pfx with known password by making a pem/key then converting it
# includes minikube and docker ips
RUN mkcert -install \
    && mkcert -key-file docker-dev.key -cert-file docker-dev.pem dockernat 10.0.75.1 localhost 127.0.0.1 web \
    && openssl pkcs12 -export -out docker-dev.pfx -inkey docker-dev.key -in docker-dev.pem -certfile rootCA.pem -passout pass:poseidon


FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine as base

WORKDIR /src

COPY ["kognifai.IdentityProvider/kognifai.IdentityProvider.csproj", "kognifai.IdentityProvider/"]
COPY ["kognifai.IdentityProvider/NuGet.config", "kognifai.IdentityProvider/"]
COPY ["kognifai.Entitlements.API.Client/kognifai.Entitlements.API.Client.csproj", "kognifai.Entitlements.API.Client/"]
RUN dotnet restore "kognifai.IdentityProvider/kognifai.IdentityProvider.csproj"
COPY . ./
WORKDIR /src/kognifai.IdentityProvider
#RUN dotnet build "kognifai.IdentityProvider.csproj" -c Debug -o /app

#FROM base AS publish
RUN dotnet publish "kognifai.IdentityProvider.csproj" -c Debug -o /dist

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine

COPY --from=cert /bin/mkcert /bin/mkcert
# root cert but not root private key:
COPY --from=cert /root/.local/share/mkcert/rootCA.pem /root/.local/share/mkcert/rootCA.pem
COPY --from=cert /root/.local/share/mkcert/docker-dev.pfx /app/
# TODO: consider `chmod 600 *.pem and *.pfx`

# tell ASP.NET Core to use the cert
ENV Kestrel__Certificates__Default__Path=/app/docker-dev.pfx
ENV Kestrel__Certificates__Default__Password=poseidon

# trust root cert
RUN apk update \
    && apk add nss-tools \
    && rm -rf /var/cache/apk/* \
    && mkcert -install \
    && apk del nss-tools \
    && rm -rf /bin/mkcert


#FROM base AS final

WORKDIR /app
VOLUME /app/kognifai.IdentityProvider/db
# VOLUME /app/kognifai.IdentityProvider

COPY --from=base /dist /app

RUN ls
RUN pwd

#COPY kognifai.IdentityProvider/db/local.litedb /app/kognifai.IdentityProvider/db/local.litedb
#COPY ["kognifai.IdentityProvider/db/local.litedb", "/app/db/local.litedb"]

ENV ASPNETCORE_ENVIRONMENT Development
ENV ASPNETCORE_URLS https://+:9445;http://+:9002
EXPOSE 9002 9445

CMD ["dotnet", "kognifai.IdentityProvider.dll"]
```
Override
```
version: '3.4'

services:
  kognifai.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTPS_PORT=9445
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
           
    ports:
      - "9002:9002"
      - "9445:9445"      
    volumes:
      # - ${CERTIFICATE_PATH}:/root/.aspnet/https:ro
         - "./db:/app/db"
      # - ".:/app/kognifai.IdentityProvider/db"
```

**Comment by rahulsahay19** [comment]
Not even with copy command like this 
COPY --from=base /dist /app
COPY db/local.litedb /app/db/local.litedb
and in override no volumes.

**Comment by rahulsahay19** [comment]
So, actually, when I do base as publish and call the same from publish during dist copy. Then it loads the litedb file. But, at that time cert becomes invalid.

```
FROM golang:alpine as cert

RUN apk update \
    && apk add git openssl nss-tools \
    && rm -rf /var/cache/apk/*

RUN cd /go && \
    go get -u github.com/FiloSottile/mkcert && \
    cd src/github.com/FiloSottile/mkcert && \
    go build -o /bin/mkcert

WORKDIR /root/.local/share/mkcert
# copied from %localappdata%\mkcert

COPY ./kognifai.IdentityProvider/rootCA*.pem /root/.local/share/mkcert/


# make a pfx with known password by making a pem/key then converting it
# includes minikube and docker ips
RUN mkcert -install \
    && mkcert -key-file docker-dev.key -cert-file docker-dev.pem dockernat 10.0.75.1 localhost 127.0.0.1 web \
    && openssl pkcs12 -export -out docker-dev.pfx -inkey docker-dev.key -in docker-dev.pem -certfile rootCA.pem -passout pass:poseidon


FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine as base

WORKDIR /src

COPY ["kognifai.IdentityProvider/kognifai.IdentityProvider.csproj", "kognifai.IdentityProvider/"]
COPY ["kognifai.IdentityProvider/NuGet.config", "kognifai.IdentityProvider/"]
COPY ["kognifai.Entitlements.API.Client/kognifai.Entitlements.API.Client.csproj", "kognifai.Entitlements.API.Client/"]
RUN dotnet restore "kognifai.IdentityProvider/kognifai.IdentityProvider.csproj"
COPY . ./
WORKDIR /src/kognifai.IdentityProvider
#RUN dotnet build "kognifai.IdentityProvider.csproj" -c Debug -o /app

FROM base AS publish
RUN dotnet publish "kognifai.IdentityProvider.csproj" -c Debug -o /dist

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine

COPY --from=cert /bin/mkcert /bin/mkcert
# root cert but not root private key:
COPY --from=cert /root/.local/share/mkcert/rootCA.pem /root/.local/share/mkcert/rootCA.pem
COPY --from=cert /root/.local/share/mkcert/docker-dev.pfx /app/
# TODO: consider `chmod 600 *.pem and *.pfx`

# tell ASP.NET Core to use the cert
ENV Kestrel__Certificates__Default__Path=/app/docker-dev.pfx
ENV Kestrel__Certificates__Default__Password=poseidon

# trust root cert
RUN apk update \
    && apk add nss-tools \
    && rm -rf /var/cache/apk/* \
    && mkcert -install \
    && apk del nss-tools \
    && rm -rf /bin/mkcert
    

#FROM base AS final

WORKDIR /app
# VOLUME [ "/kognifai.IdentityProvider/kognifai.IdentityProvider/db" ]
VOLUME /kognifai.IdentityProvider/db
# VOLUME /app/kognifai.IdentityProvider

COPY --from=publish/dist /app
# COPY db/local.litedb /app/db/local.litedb
RUN ls
RUN pwd

#COPY kognifai.IdentityProvider/db/local.litedb /app/kognifai.IdentityProvider/db/local.litedb
#COPY ["kognifai.IdentityProvider/db/local.litedb", "/app/db/local.litedb"]

ENV ASPNETCORE_ENVIRONMENT Development
ENV ASPNETCORE_URLS https://+:9445;http://+:9002
EXPOSE 9002 9445

CMD ["dotnet", "kognifai.IdentityProvider.dll"]
```
with override 
```
version: '3.4'

services:
  kognifai.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_HTTPS_PORT=9445
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
           
    ports:
      - "9002:9002"
      - "9445:9445"      
    volumes:
      # - ${CERTIFICATE_PATH}:/root/.aspnet/https:ro
      # - "./kognifai.IdentityProvider/db:/db"
      # - "./app/db:/db"
      # - "./kognifai.IdentityProvider/local.litedb:/local.litedb"
      - "./kognifai.IdentityProvider/db:/app/db"
```
Then, it loads the litedb screen. But, at this stage, api becomes unsecure. Hence, cert issue comes while calling another api from this. looks like multi stage issue is happening here.

**Comment by rahulsahay19** [comment]
Like in your example repo of mkcert, if you just have one litedb and try to access via some api, then i think you can replicate volume failure in your repo as well.

**Comment by rahulsahay19** [comment]
Hi Rob,

Manage to solve this volume issue by putting FROM base AS final before COPY --from=cert /bin/mkcert /bin/mkcert. Although certs are inherited mkcert only. But my api is still giving 
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'. ---> System.Net.Http.HttpRequestException: Address not available ---> System.Net.Sockets.SocketException.

basically it gives, 
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:9445/.well-known/openid-configuration'.
when i make IdentityModelEventSource.ShowPII = true; in api.

![image](https://user-images.githubusercontent.com/3886381/69958300-81e06d00-152a-11ea-94d8-254c87347f94.png)

![image](https://user-images.githubusercontent.com/3886381/69958340-9886c400-152a-11ea-9e3a-568456378ce2.png)

And another one also 
![image](https://user-images.githubusercontent.com/3886381/69958382-b3f1cf00-152a-11ea-8037-2e6c735615e9.png)

![image](https://user-images.githubusercontent.com/3886381/69958421-cc61e980-152a-11ea-969e-bd19dab41778.png)

Anything I am doing wrong here. Same way I composed both the docker files.

Thanks,
Rahul

**Comment by rahulsahay19** [comment]
I see, you have one compose file that's why with link its working. In my case, these are different projects, hence different compose file. Not sure, if I can use links or some kind of network between them.

**Comment by robrich** [comment]
Good catch. If they're different compose files, by default they get different Docker networks.  Check out the external keyword in https://docs.docker.com/compose/networking/  My general rule-of-thumb is one Dockerfile per project, and one docker-compose.yaml per solution.

**Comment by rahulsahay19** [comment]
Yeah same thing I am trying and I have put this in "AuthorityURL": "https://identityprovider:9445/", since identityprovider is different service and its compose looks like 

```version: '3.4'

networks:
    default:
        external:
            name: pnext-network

services:
  poseidonapi:
    image: ${DOCKER_REGISTRY}pnext-api:dev
    build:
      context: .
      dockerfile: Poseidon.Api/Dockerfile
    container_name: pnext-api
    external_links: ["identityprovider"]
  ```
And the other one which is idp. Its compose looke like

```
version: '3.4'

networks:
    default:
        external:
            name: pnext-network

services:
  identityprovider:
    image: ${DOCKER_REGISTRY}pnext-idp:dev
    build:
      context: .
      dockerfile: kognifai.IdentityProvider/Dockerfile
    container_name: pnext-idp    
```
And override for both are usual. But, when its calling api looks like unable to understand https://identityprovider:9445/ and hence 401 is coming as bearer token not getting picked up. I am guessing in case of external network. this https://identityprovider:9445/ needs to be configured little differently.
